### ISSUE TITLE
Please add Kotlin 2.0

### ISSUE THREAD

**Issue by Stummi** [yawkat/javap#17]
I tried to do it my self and open a Pull Request, but I couldn't get the project building on my machine for some reason.. Maybe I will have a closer look  on that later.

The Kotlin 2.0 release comes with a whole new Kotlin compiler (K2), and your tool could be especially useful here to investigate difference in produced bytecode. Please consider adding Kotlin 2.0 to the supported Compilers

**Comment by yawkat** [comment]
ive done a bunch of updates, incl adding kotlin 2.0.10. please test as well, im not familiar with the new features.

**Comment by Stummi** [comment]
Works like a charm at first glance, thank you very much :)
